# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|  
  (1..2).each do |i|
    config.vm.define "Node-#{i}" do |node|
      node.vm.box = "ubuntu/focal64"
      #node.vm.network "private_network", ip: "192.168.100.2#{i}"
	    node.vm.network "public_network", bridge: "Qualcomm Atheros AR9485WB-EG Wireless Network Adapter", adapter: "1", use_dhcp_assigned_default_route: true
      node.vm.synced_folder ".", "/vagrant", disabled: true
      node.vm.boot_timeout = 120

      config.vm.provider "virtualbox" do |vb|
        # Customize the amount of memory on the VM:
        #vb.name   = "Kubernetes - Node #{i}"
        vb.memory = "2048"
        vb.cpus   = "2"
      end

      config.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y net-tools
      SHELL
      
    end
  end
end